### ISSUE TITLE
Possible crash with new Primal 0.6.57

### ISSUE THREAD

**Issue by Adarcer** [An-Sar/MagnumOpus#2]
https://paste.dimdev.org/uqaqabupoq.mccrash

MagnumOpus-1.12.2-0.0.19 

besides primal i updated "better underground", removed the cauldron line also...
Added "interaction wheel" <-- still crashes when disabled
on a side note log spam seems gone

**Comment by An-Sar** [comment]
A new Magnum beta is dropping soon which will fix this

**Comment by Adarcer** [comment]
Cool thanks ... knew you would get it fixed. just gave the crash report to possibly narrow down the problem

**Comment by An-Sar** [comment]
i appreciate the detailed report!
