### ISSUE TITLE
Server crash on startup after update PrimalCore

### ISSUE THREAD

**Issue by Bulldog83** [An-Sar/MagnumOpus#4]
After I've updated PrimalCore to version 0.6.58 the server crashes on startup.

Minecraft 1.12.2
Forge 14.23.4.2705
PrimalCore 0.6.58
Magnum 0.0.20

https://gist.github.com/Bulldog83/d5fe217e29b394b3e2e5b8f5307a140f

**Comment by An-Sar** [comment]
a new alpha build is (0.0.21) is coming very soon with a fix
